BookHub/Models/Buyer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BookHub.Models
{
    public class Buyer
    {
        public int BuyerID { get; set; }
        public int UserID { get; set; }
        public User User { get; set; }

         [Required(ErrorMessage = "Your must provide a First Name")]
        [Display(Name="First Name")]
        public string fname { get; set; }

         [Required(ErrorMessage = "Your must provide a Last Name")]
         [Display(Name = "Last Name")]
        public string lname { get; set; }
       // public string gender { get; set; }

        [Required(ErrorMessage = "You must provide a PhoneNumber")]
        [Display(Name = "Contact Number")]
        [DataType(DataType.PhoneNumber)]
       [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid Phone number")]
        public string contact { get; set; }

        [Display(Name="Address")]
        public string addr { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string Landmark { get; set; }
        public ICollection<Address> Addresses { get; set; }
   

    }
}

BookHub/Controllers/BuyerController.cs
using BookHub.Models;
using BookHub.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web;

namespace BookHub.Controllers
{
    public class BuyerController : Controller
    {
        // GET: /Buyer/
       BookHub.DAL.MyContextClass db = new BookHub.DAL.MyContextClass();
        public ActionResult Index()
        {
            BuyerAndBookAndSellerViewModel bb = new BuyerAndBookAndSellerViewModel();
            bb.BookAndSellerMapDisplays = getBookAndSellers();
            bb.SliderContents = getSlider();
            return View(bb);
        }
        public List<SliderContent> getSlider()
        {                 
            var list = db.SliderContents.OrderBy(x => x.SliderContentId).ToList();
            return list;
        }
        public List<BookAndSellerMapDisplay> getBookAndSellers()
        {
            var bookandsellermapsprop = db.BookAndSellerMapDisplays.Include(b => b.BookAndSellerMap.Book).Include(b => b.BookAndSellerMap.BookFormat).Include(b => b.BookAndSellerMap.Language).Include(b => b.BookAndSellerMap.Seller).OrderByDescending(n => n.BookAndSellerMap.CreatedOn);
            return bookandsellermapsprop.ToList();
        }
        public ActionResult Details2(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookAndSellerMap bookandsellermap = db.BookAndSellerMapsprop.Include(w => w.Book).Include(q => q.Seller).Include(q => q.BookFormat).Include(q => q.Language).Include(s => s.Files).SingleOrDefault(s => s.BookAndSellerMapID == id);
            if (bookandsellermap == null)
            {
                return HttpNotFound();
            }
            return View(bookandsellermap);
        }
        public ActionResult ProfileView(Buyer buyers)
        {
            string sessUname = Session["Uname"].ToString();
           
                int sess = Convert.ToInt32(Session["UID"]);
                var buyer = db.Buyers.Where(b => b.User.username == sessUname).FirstOrDefault().BuyerID;
                var profile = db.Buyers.Where(b => b.BuyerID == buyer).Select(b => b).Include(b=>b.User).FirstOrDefault();
                if (profile == null)
            {
                return HttpNotFound();
            }
                return View(profile);
        }
        public ActionResult EditProfile(int? id)
        {
            if(id==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Buyer buyer = db.Buyers.Find(id);
            if(buyer==null)
            {
                return HttpNotFound();
            }
            return View(buyer);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProfile(Buyer buyers)
        {
            string sessUname = Session["Uname"].ToString();
            int sess = Convert.ToInt32(Session["UID"]);
            var item = db.Buyers.Where(b => b.User.username == sessUname).FirstOrDefault().BuyerID;
            var buyer = db.Buyers.Where(b => b.BuyerID == item).Select(b => b).FirstOrDefault();
            buyer.addr = buyers.addr;
            buyer.city = buyers.city;
            buyer.contact=buyers.contact;
            buyer.country=buyers.country;
            buyer.fname = buyers.fname;
            buyer.Landmark = buyers.Landmark;
            buyer.lname = buyers.lname;
            buyer.state = buyers.state;   
   
            if (ModelState.IsValid)
            {
                db.Entry(buyer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ProfileView");
            }
            return View(buyers);
        }
        public ActionResult MyOrder(Order order)
        {
            string SUname = Session["Uname"].ToString();
            int sess = Convert.ToInt32(Session["UID"]);
            var buyer = db.Buyers.Where(b => b.UserID==sess).FirstOrDefault().BuyerID;
            var Myorder=db.OrderItems.Where(o=>o.Order.BuyerID==buyer).Select(x=>x).Include(b=>b.BookAndSellerMap).Include(b=>b.BookAndSellerMap.Book).ToList();
            var orders = db.Orders.Where(b => b.BuyerID == buyer).Select(x=>x).FirstOrDefault();
            
            return View(Myorder);
        }
    }
}

BookHub/Views/Buyer/Details2.cshtml
@model BookHub.Models.BookAndSellerMap
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}

<h2>Details</h2>

<div>
    <h4>BookAndSellerMap</h4>
    <hr />
    <dl class="dl-horizontal">
        @if (Model.Files.Any(f => f.FileType == FileType.Avatar))
        {
            <dt>
                Image
            </dt>
            <dd>
                <img width="360" height="310" src="~/File?id=@Model.Files.First(f => f.FileType == FileType.Avatar).FileId" alt="avatar" />
            </dd>
        }
        <dt>
            @Html.DisplayNameFor(model => model.Book.BookName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Book.BookName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookFormat.BookFormatName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookFormat.BookFormatName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Language.LanguageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language.LanguageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Seller.fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Seller.fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Publication)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Publication)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PageCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PageCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrintYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrintYear)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FinalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinalPrice)
        </dd>
    </dl>
</div>
<p>
   
    @Html.ActionLink("Back to List", "Index")
</p>

BookHub/Views/Buyer/EditProfile.cshtml
@model BookHub.Models.Buyer

@{
    ViewBag.Title = "EditProfile";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}

<h2>EditProfile</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Buyer</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.BuyerID)

       

        <div class="form-group">
            @Html.LabelFor(model => model.fname, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fname)
                @Html.ValidationMessageFor(model => model.fname)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lname, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lname)
                @Html.ValidationMessageFor(model => model.lname)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contact, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contact)
                @Html.ValidationMessageFor(model => model.contact)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.addr, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.addr)
                @Html.ValidationMessageFor(model => model.addr)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city)
                @Html.ValidationMessageFor(model => model.city)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.state, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.state)
                @Html.ValidationMessageFor(model => model.state)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.country, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.country)
                @Html.ValidationMessageFor(model => model.country)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Landmark, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Landmark)
                @Html.ValidationMessageFor(model => model.Landmark)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BookHub/Views/Buyer/Index.cshtml
@model BookHub.ViewModels.BuyerAndBookAndSellerViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}




<link href="~/Content/main.css" rel="stylesheet" />

@{
    var message = TempData["AlertMessage"] ?? string.Empty;
}

<script type="text/javascript">
    var message = '@message';
    if(message)
        alert(message);
    message = null;
</script>


@{
    message = null;
    TempData["AlertMessage"] = null;
}


<section id="slider">
    <!--slider-->
    <div class="container">
       
@{
    int count = Model.SliderContents.Count();
    BookHub.DAL.MyContextClass db = new BookHub.DAL.MyContextClass();
    var SliderCon = db.SliderContents;
    if(count>0)
    { 
     <div class="row">
            <div class="col-sm-12">
                <div id="slider-carousel" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">



                        <li data-target="#slider-carousel" data-slide-to="0" class="active"></li>

                       @for(int i=1;i<count;i++)
                        {
                         <li data-target="#slider-carousel" data-slide-to="@i"></li>
                        }
                    </ol>

                    <div class="carousel-inner" >

                            <div class="item active">
                            <div class="col-sm-6">
                                <h1><span>B</span>ook<span>H</span>ub <span>S</span>pecial <span>O</span>ffer</h1>
                                <h2>@SliderCon.First().SliderHeading</h2>
                                <p>@SliderCon.First().SliderSubHeading</p>
                                <button type="button" class="btn btn-default get">Get it now</button>
                            </div>
                            <div class="col-sm-6">
                                <img width="300" height="260" src="~/SliderData?id=@SliderCon.First().SliderDatas.First(f => f.FileType == FileType.Photo).SliderDataId" alt="photo" />
                                <img src="~/Content/images/home/pricing.png" class="pricing" alt="" />
                            </div>
                            </div>
                   
                   


                            @for (int j = 1; j < count;j++ )
                            {
                                var item = Model.SliderContents.ElementAt(j);
                                <div class="item">
                            <div class="col-sm-6">
                                <h1><span>B</span>ook<span>H</span>ub <span>S</span>pecial <span>O</span>ffer</h1>
                                <h2>@item.SliderHeading</h2>
                                <p>@item.SliderSubHeading</p>
                                <button type="button" class="btn btn-default get">Get it now</button>
                            </div>
                            <div class="col-sm-6">
                                <img width="300" height="260" src="~/SliderData?id=@item.SliderDatas.First(f => f.FileType == FileType.Photo).SliderDataId" alt="photo" />
                                <img src="~/Content/images/home/pricing.png" class="pricing" alt="" />
                            </div>
                            </div>
                                
                            }
                            
                            
                            
                            
               
                            


                    </div>

                    <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
                        <i class="fa fa-chevron-circle-left"></i>
                    </a>
                    <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
                        <i class="fa fa-chevron-circle-right"></i>
                    </a>
                </div>

            </div>
        </div>
}  
    
}
    
    </div>
</section>







<div class="col-sm-9 padding-right">
    <div class="features_items">
        <!--features_items-->
        <h2 class="title text-center">Featured Items</h2>

@foreach(var item in Model.BookAndSellerMapDisplays)
{
    
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">


                      
                        <img src="~/File?id=@item.BookAndSellerMap.Files.First(f => f.FileType == FileType.Avatar).FileId" alt="avatar" />

                        <h2>Rs. @item.BookAndSellerMap.Price</h2>
                        <p>@item.BookAndSellerMap.Book.BookName</p>

                     
                          

                        @*<a href="" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>*@
                    </div>
                    <div class="product-overlay">
                        <div class="overlay-content">
                            <h2>Rs. @item.BookAndSellerMap.Price</h2>
                            @*<p>@item.BookAndSellerMap.Book.BookName</p>*@
                            <p class="button">
                                @Html.ActionLink(@item.BookAndSellerMap.Book.BookName, "Details2",
               "Buyer", new { id = item.BookAndSellerMap.BookAndSellerMapID},"")
                            </p>

                            @*<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>*@
                            <p class="button">
                                @Html.ActionLink("Add to cart", "AddToCart",
               "ShoppingCart", new { id = item.BookAndSellerMapId }, "")
                            </p>
                            <p class="button">
                                @Html.ActionLink("Add to wishlist", "AddToWishList",
               "WishList", new { id = item.BookAndSellerMapId }, "")
                            </p>
                        </div>
                    </div>
                </div>
                @*<div class="choose">
                    <ul class="nav nav-pills nav-justified">
                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                    </ul>
                </div>*@
            </div>
        </div>
    
}



        

    </div><!--features_items-->
    </div>

   

BookHub/Views/Buyer/MyOrder.cshtml
@model IEnumerable<BookHub.Models.OrderItem>

@{
    ViewBag.Title = "MyOrder";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}

<h2>MyOrder</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BookAndSellerMap.Book.BookName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookAndSellerMap.Publication)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderItemStatus)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BookAndSellerMap.Book.BookName)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.BookAndSellerMap.Publication)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderItemStatus)
        </td>
        
    </tr>
}

</table>

BookHub/Views/Buyer/ProfileView.cshtml
@model BookHub.Models.Buyer
@{
    ViewBag.Title = "ProfileView";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}
<h2>ProfileView</h2>

<div>
    <h4>Buyer</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.addr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.addr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Landmark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Landmark)
        </dd>

    </dl>
</div>

<p style="text-align:match-parent">
    @Html.ActionLink("UpdateProfile", "EditProfile", new { id = Model.BuyerID })

</p>