BookHub/ViewModels/ShoppingCartViewModel.cs
using BookHub.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookHub.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<CartItem> CartItems { get; set; }
        public Cart Cart { get; set; }
        public float CartTotal { get; set; }


    }
}

BookHub/Controllers/ShoppingCartController.cs
using BookHub.DAL;
using BookHub.Models;
using BookHub.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Core;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BookHub.Controllers
{
    public class ShoppingCartController : Controller
    {
        MyContextClass db = new MyContextClass();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            int sess = Convert.ToInt32(Session["Uid"]);
            int buyerid = db.Buyers.Where(b => b.UserID.Equals(sess)).FirstOrDefault().BuyerID;
            var cart = db.Carts.Where(c => c.BuyerID.Equals(buyerid)).Include(e => e.CartItems).FirstOrDefault();
            ShoppingCartViewModel scvm = new ShoppingCartViewModel();
            scvm.Cart = cart;
            scvm.CartItems = getCartItems(cart);
            scvm.CartTotal = getCartTotal(cart);
            return View(scvm);
        }
        public ActionResult AddToCart(int? id)
        {
            var bookRecToAdd = db.BookAndSellerMapsprop.Find(id);

            int sess = Convert.ToInt32(Session["Uid"]);
            int buyerid = db.Buyers.Where(b => b.UserID.Equals(sess)).FirstOrDefault().BuyerID;
            var cart = db.Carts.Where(c => c.BuyerID.Equals(buyerid)).FirstOrDefault();
            var cartItem = new CartItem();

            if (cart == null)
            {
                cart = new Cart
                {
                    BuyerID = buyerid,
                    Total = 0,
                    CreatedOn = DateTime.Now
                };
                db.Carts.Add(cart);
                db.SaveChanges();
            }

            cartItem = new CartItem
            {
                BookAndSellerMapID = bookRecToAdd.BookAndSellerMapID,
                CartID = cart.CartID,
                Quantity = 0,
                CreatedOn = DateTime.Now
            };
            db.CartItems.Add(cartItem);
            cartItem.Quantity++;
            cart.Total = cart.Total + bookRecToAdd.FinalPrice;
            // db.Entry(cart).State = EntityState.Modified;
            db.SaveChanges();

            TempData["AlertMessage"] = "Book Successfully added to your cart";
            return Redirect(Request.UrlReferrer.ToString());
        }
        public float getCartTotal(Cart cart)
        {
            float tot = cart.Total;
            return tot;
        }
        public List<CartItem> getCartItems(Cart cart)
        {
            var cartItems = db.CartItems.Where(t => t.CartID.Equals(cart.CartID)).Include(q => q.BookAndSellerMap).Include(w => w.BookAndSellerMap.Book);
            return cartItems.ToList();
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int cartItemID = db.CartItems.Find(id).CartItemID;
            var item1 = db.CartItems.Include(s => s.BookAndSellerMap).Include(w => w.BookAndSellerMap.Book);
            var item = item1.Where(a => a.CartItemID.Equals(cartItemID)).FirstOrDefault();
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: /BookForSeller/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CartItem item = db.CartItems.Find(id);
            int sess = Convert.ToInt32(Session["Uid"]);
            int buyerid = db.Buyers.Where(b => b.UserID.Equals(sess)).FirstOrDefault().BuyerID;
            var cart = db.Carts.Where(c => c.BuyerID.Equals(buyerid)).FirstOrDefault();

            cart.CartItems.Remove(item);
            cart.Total -= item.BookAndSellerMap.FinalPrice * item.Quantity;

            db.CartItems.Remove(item);
            db.Entry(cart).State = EntityState.Modified;

            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DeleteAll(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var item = db.Carts.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }
        // POST: /BookForSeller/DeleteAll/5
        [HttpPost, ActionName("DeleteAll")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAllConfirmed(int id)
        {
            Cart cart = db.Carts.Find(id);
            var cartItems = db.CartItems.Where(w => w.CartID.Equals(cart.CartID));

            foreach (var item in cartItems)
            {
                cart.CartItems.Remove(item);
                db.CartItems.Remove(item);
            }
            cart.Total = 0;
            db.Entry(cart).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CheckoutCart(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            if (cart.Total <= 0)
            {
                ModelState.AddModelError("", "You Cannot Proceed to checkout as your cart value is Zero. Kindly add some items to your cart first.");
            }
            return RedirectToAction("SelectAddress");
        }
        public ActionResult SelectAddress()
        {
            int sess = Convert.ToInt32(Session["Uid"]);
            var buyeridz = db.Buyers.Where(b => b.UserID.Equals(sess)).FirstOrDefault();
            int buyerid = buyeridz.BuyerID;

            var addresses = db.Addresses.Where(a => a.BuyerID.Equals(buyerid)).Include(s => s.Buyer);
            return View(addresses);
        }
        public ActionResult AddAddress()
        {
            return View();
        }
        // POST: /Address/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAddress([Bind(Include = "AddressID,fname,lname,contact,addr,city,state,country,Landmark")] Address address)
        {
            int sess = Convert.ToInt32(Session["Uid"]);
            var buyeridz = db.Buyers.Where(b => b.UserID.Equals(sess)).FirstOrDefault();
            int buyerid = buyeridz.BuyerID;
            address.BuyerID = buyerid;
            if (ModelState.IsValid)
            {
                db.Addresses.Add(address);
                db.SaveChanges();
                return RedirectToAction("SelectAddress");
            }
            return View(address);
        }

        // GET: /Address/Edit/5
        public ActionResult EditAddress(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = db.Addresses.Find(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }
        // POST: /Address/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditAddress([Bind(Include = "AddressID,BuyerID,fname,lname,contact,addr,city,state,country,Landmark")] Address address)
        {
            if (ModelState.IsValid)
            {
                db.Entry(address).State = EntityState.Modified;

                db.SaveChanges();
                return RedirectToAction("SelectAddress");
            }
            return View(address);
        }
        // GET: /Address/Delete/5
        public ActionResult DeleteAddress(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = db.Addresses.Find(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }

        // POST: /Address/Delete/5
        [HttpPost, ActionName("DeleteAddress")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAddressConfirmed(int id)
        {
            Address address = db.Addresses.Find(id);
            db.Addresses.Remove(address);
            db.SaveChanges();
            return RedirectToAction("SelectAddress");
        }
        public ActionResult DeliverHere(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = db.Addresses.Find(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            int sess = Convert.ToInt32(Session["Uid"]);
            int buyerid = db.Buyers.Where(b => b.UserID.Equals(sess)).FirstOrDefault().BuyerID;
            var cartForOrder = db.Carts.Where(c => c.BuyerID.Equals(buyerid)).Include(f => f.CartItems).FirstOrDefault();

            Order1 newOrder = new Order1();
            newOrder.Address = address;
            newOrder.Cart = cartForOrder;
            newOrder.PaymentOptions = db.PaymentOptions.ToList();
            newOrder.SelectedPayment = 0;
            return View(newOrder);
        }
        [ValidateAntiForgeryToken]
        public ActionResult PayNow(Order1 order1)
        {

BookHub/Views/ShoppingCart/AddAddress.cshtml
@model BookHub.Models.Address

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}

<h2>Add New Address</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Address</h4>
        <hr />
        @Html.ValidationSummary(true)

        

        <div class="form-group">
            @Html.LabelFor(model => model.fname, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fname)
                @Html.ValidationMessageFor(model => model.fname)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lname, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lname)
                @Html.ValidationMessageFor(model => model.lname)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contact, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contact)
                @Html.ValidationMessageFor(model => model.contact)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.addr, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.addr)
                @Html.ValidationMessageFor(model => model.addr)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city)
                @Html.ValidationMessageFor(model => model.city)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.state, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.state)
                @Html.ValidationMessageFor(model => model.state)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.country, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.country)
                @Html.ValidationMessageFor(model => model.country)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Landmark, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Landmark)
                @Html.ValidationMessageFor(model => model.Landmark)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "SelectAddress")
</div>

BookHub/Views/ShoppingCart/CartSummary.cshtml
@Html.ActionLink("Your Cart(" + ViewData["CartCount"] + ")","Index",
"ShoppingCart",
    new { id = "cart-status" })

BookHub/Views/ShoppingCart/Delete.cshtml
@model BookHub.Models.CartItem

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CartItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BookAndSellerMap.Book.BookName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookAndSellerMap.Book.BookName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BookAndSellerMap.Book.AuthorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookAndSellerMap.Book.AuthorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CartID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CartID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BookHub/Views/ShoppingCart/DeleteAddress.cshtml
@model BookHub.Models.Address

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this Address permanently?</h3>
<div>
    <h4>Address</h4>
    <hr />
    <dl class="dl-horizontal">
       

        <dt>
            @Html.DisplayNameFor(model => model.fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.addr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.addr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Landmark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Landmark)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BookHub/Views/ShoppingCart/DeleteAll.cshtml
@{
    ViewBag.Title = "DeleteAll";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}

<h2>Are You Sure You Want To Empty Your Cart? </h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="DeleteAll" class="btn btn-default" /> 
        @Html.ActionLink("Back to List", "Index")
    </div>
}

BookHub/Views/ShoppingCart/DeliverHere.cshtml
@model BookHub.ViewModels.Order1
@{
    ViewBag.Title = "DeliverHere";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}



<h3> Your Order Can be delivered at @Model.Address.addr, @Model.Address.city, @Model.Address.state, @Model.Address.country in 3-5 Business Days </h3>
<h3 style="color: #FE980F" >
    Select Payment method:
</h3>
@using (Html.BeginForm("PayNow", "ShoppingCart"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => Model.Address.addr)
        @Html.HiddenFor(model => model.Address.AddressID)
        @Html.HiddenFor(model => model.Address.Buyer)
        @Html.HiddenFor(model => model.Address.BuyerID)
        @Html.HiddenFor(model => model.Address.city)
        @Html.HiddenFor(model => model.Address.contact)
        @Html.HiddenFor(model => model.Address.country)
        @Html.HiddenFor(model => model.Address.fname)
        @Html.HiddenFor(model => model.Address.isDefault)
        @Html.HiddenFor(model => model.Address.Landmark)
        @Html.HiddenFor(model => model.Address.lname)
        @Html.HiddenFor(model => model.Address.state)
 



        @Html.HiddenFor(model => Model.Cart.Buyer)
        @Html.HiddenFor(model => Model.Cart.BuyerID)
        @Html.HiddenFor(model => Model.Cart.CartID)
        @Html.HiddenFor(model => Model.Cart.CartItems)
        @Html.HiddenFor(model => Model.Cart.CreatedOn)
        @Html.HiddenFor(model => Model.Cart.Total)

       

        @Html.HiddenFor(model => Model.PaymentOptions)
        <div class="form-group">


            <div class="col-md-10">

                <h4>

                    @foreach (var t in Model.PaymentOptions)
                    {
                        @Html.RadioButtonFor(model => Model.SelectedPayment, t.PaymentOptionID ) @t.PaymentOptionName

                        <br /> <br />
                    }
                </h4>
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Pay Now" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BookHub/Views/ShoppingCart/EditAddress.cshtml
@model BookHub.Models.Address

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Address</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.AddressID)
        @Html.HiddenFor(model => model.BuyerID)

     

        <div class="form-group">
            @Html.LabelFor(model => model.fname, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fname)
                @Html.ValidationMessageFor(model => model.fname)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lname, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lname)
                @Html.ValidationMessageFor(model => model.lname)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contact, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contact)
                @Html.ValidationMessageFor(model => model.contact)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.addr, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.addr)
                @Html.ValidationMessageFor(model => model.addr)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city)
                @Html.ValidationMessageFor(model => model.city)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.state, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.state)
                @Html.ValidationMessageFor(model => model.state)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.country, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.country)
                @Html.ValidationMessageFor(model => model.country)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Landmark, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Landmark)
                @Html.ValidationMessageFor(model => model.Landmark)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "SelectAddress")
</div>

BookHub/Views/ShoppingCart/Index.cshtml
@model BookHub.ViewModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}
                                   
<h2>Your Cart</h2>
<h3>
    @Html.ActionLink("Empty Cart", "DeleteAll", new { id = Model.Cart.CartID})
</h3>
<table class="table" style="border:inherit">
    <tr>
        <th>
            Book Name
        </th>
        <th>
            Author's Name
        </th>
        <th>
            Quantity
        </th>
        <th>
            Original Price
        </th>
        <th>
            Discount
        </th>
        <th>
            Price For You
        </th>
        <th>
            Image
        </th>
    </tr>
    @foreach (var item in Model.CartItems)
    {
        <tr>
            <td>
                @item.BookAndSellerMap.Book.BookName
            </td>
            <td>
                @item.BookAndSellerMap.Book.AuthorName
            </td>
            <td>
                @item.Quantity
            </td>
            <td>
                @item.BookAndSellerMap.Price
            </td>
            
            <td>
                @item.BookAndSellerMap.Discount
            </td>
            <td>
                @item.BookAndSellerMap.FinalPrice
            </td>
            <td>

                <img width="200" height="200" src="~/File?id=@item.BookAndSellerMap.Files.First(f => f.FileType == FileType.Avatar).FileId" alt="avatar" />
            </td>
            <td>
                @Html.ActionLink("Remove", "Delete", new { id = item.CartItemID })
    
            </td>
        <td>
            <p class="button">
                @Html.ActionLink("Add to wishlist", "AddToWish", new { id = item.CartItemID })
            </p>
          
            </td>
        </tr>
        

    }

</table>


<br /><br />
<h2>
    Your Cart Total is: @Model.CartTotal
</h2>

@if(Model.CartTotal>0)
{ 
<h3>
    @Html.ActionLink("Proceed to Checkout", "CheckoutCart", new { id = Model.Cart.CartID })
</h3>
}

BookHub/Views/ShoppingCart/PayNow.cshtml
@model BookHub.ViewModels.Order1
@{
    ViewBag.Title = "PayNow";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}







<h1>  Payment Page  </h1>


@using (Html.BeginForm("OrderPlacing", "ShoppingCart", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => Model.Address.addr)
        @Html.HiddenFor(model => model.Address.AddressID)
        @Html.HiddenFor(model => model.Address.Buyer)
        @Html.HiddenFor(model => model.Address.BuyerID)
        @Html.HiddenFor(model => model.Address.city)
        @Html.HiddenFor(model => model.Address.contact)
        @Html.HiddenFor(model => model.Address.country)
        @Html.HiddenFor(model => model.Address.fname)
        @Html.HiddenFor(model => model.Address.isDefault)
        @Html.HiddenFor(model => model.Address.Landmark)
        @Html.HiddenFor(model => model.Address.lname)
        @Html.HiddenFor(model => model.Address.state)




        @Html.HiddenFor(model => Model.Cart.Buyer)
        @Html.HiddenFor(model => Model.Cart.BuyerID)
        @Html.HiddenFor(model => Model.Cart.CartID)
        @Html.HiddenFor(model => Model.Cart.CartItems)
        @Html.HiddenFor(model => Model.Cart.CreatedOn)
        @Html.HiddenFor(model => Model.Cart.Total)

        @Html.HiddenFor(model => Model.SelectedPayment)


        <div class="form-group">
            <div class=" col-lg-1" style="height:100px"></div> 
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Done" class="btn btn-default" />
            </div>
        </div>
    </div>
}

BookHub/Views/ShoppingCart/SelectAddress.cshtml
@model IEnumerable<BookHub.Models.Address>

@{
    ViewBag.Title = "SelectAddress";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}

<h2>SelectAddress</h2>

<p>
    @Html.ActionLink("Add a New Address", "AddAddress")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Buyer.fname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contact)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.addr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.city)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.state)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Landmark)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Buyer.fname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.lname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contact)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.addr)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.city)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.state)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Landmark)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditAddress", new { id=item.AddressID }) 
            @Html.Label(" | ")
            
            @Html.ActionLink("Details", "Details", new { id=item.AddressID }) 
            
            @if(item.isDefault==false)
            { 
          string name="| ";
               @Html.Label(name) 
            @Html.ActionLink(" Delete", "DeleteAddress", new { id=item.AddressID })
                
            }
        </td>
        <td>
            @Html.ActionLink("Deliver To This Address", "DeliverHere", new { id= item.AddressID })
        </td>
    </tr>
}

</table>

BookHub/Views/ShoppingCart/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_MyLayoutBuyerPage.cshtml";
}

<h2>Congratulations! Your Order Has Been Placed Successfully!!! </h2>
<h4>
    Click <a href="../Buyer/Index">Here</a> To Shop More...
</h4>