BookHub/Controllers/StupidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookHub.Controllers
{
    public class StupidController : Controller
    {
        //
        // GET: /Stupid/
        public ActionResult DoneWithYou1()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            Session["Uname"] = null;
            Session["UFname"] = null;
            Session["Uid"] = null;
            return RedirectToAction("Index", "Home");
        }
	}
}

BookHub/Views/Stupid/DoneWithYou.cshtml
@{
    ViewBag.Title = "LogOut";
}
@{
    Layout = "~/Views/Shared/_MyLayoutMainPage.cshtml";
}
<center><h2>Are You Sure You want To Log Out?</h2></center>

<br /><br /> 
@using (Html.BeginForm("LogOff","Stupid",FormMethod.Post))
{
   @Html.AntiForgeryToken()
  
    <div class="col-sm-4"></div>
<div class="form-group col-sm-4" style="align-content:center">
    
        <input type="submit" value="Yes" class="btn btn-success btn-lg" style="width: 400px;" />
   
</div>
<div class="col-sm-4"></div>
}
<br /><br/> <br /><br /> 
<div class="col-sm-4"></div>

<div class="form-group col-sm-4" style="align-content:center">
   
        <a href="../Buyer/BIndex" class="btn btn-success btn-lg" style="width: 280px"> No </a>
    
</div>

<div class="col-sm-4"></div>
<br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> 

BookHub/Views/Stupid/DoneWithYou1.cshtml
@{
    ViewBag.Title = "LogOut";
}
@{
    Layout = "~/Views/Shared/_MyLayoutAnyPage.cshtml";
}
<center><h2>Are You Sure You want To Log Out?</h2></center>

<br /><br />
@using (Html.BeginForm("LogOff", "Stupid", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="col-sm-4"></div>
    <div class="form-group col-sm-4" style="align-content:center">

        <input type="submit" value="Yes" class="btn btn-success btn-lg" style="width: 400px;" />

    </div>
    <div class="col-sm-4"></div>
}
<br /><br /> <br /><br />
<div class="col-sm-4"></div>

<div class="form-group col-sm-4" style="align-content:center">

    <a href="../Home/Index" class="btn btn-success btn-lg" style="width: 280px"> No </a>

</div>

<div class="col-sm-4"></div>
<br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> <br /><br /> 